webdataset/webdataset

- webdataset/autodecode.py
This is pretty spammy in logs and other similar classes don't do it.
> Remove noisy os.system call from TorchAudioLoader

- webdataset/fluid.py
Fix mentioned in #50 . 
I figure the signature should match `wds.WebDataset` exactly so you can just use `**kwargs` instead of explicitly listing the args in `wds.Dataset`'s init. However, I opted to not do that since it would introduce breaking changes to the existing `wds.Dataset` API.
> Include cache args in Dataset init

- webdataset/dataset.py
- webdataset/dbcache.py
Hey Tom! 
I've been using `webdataset` for managing our audio data pipeline and ran into a couple of blockers for our use case. 
The first change is regarding the `.batched` function in the `Shorthands` class. In master, you cannot specify a collation function to use akin to what `torch.utils.data.DataLoader` allows. The actual function responsible with batching, `iterators.batched` allows for a user-specified collation function but this is not pushed into the `Shorthands` class. A couple of reasons why this is a good feature to have are allowing batched dictionaries, complicated padding strategies, in-batch ordering of elements, ...
The second change is adding the `.source_` function to the `DBCache` class. I was simply following the `readme.ipynb` and could not get the section with the …
> collation_fn argument for batched + DBCache source_ fn

- webdataset/dataset.py
Currently 'only' argument of decode is not exposed so it cannot be defined to whitelist keys. This will enable using decode shorthand with 'only' argument.
> Update decode Shorthand to expose 'only' argument

- webdataset/composable.py
Add documentation to `to_tuple` about what `missing_is_error` and `none_is_error` are doing, and allows their usage in the chained version of `to_tuple` like so:
```python3
dataset = (
wds.WebDataset("truc_00000.tar")
.decode(wds.handle_extension("mask.png", png_decoder_1bpp))
.to_tuple("1.mask.png", "2.mask.png", "3.mask.png", "cls", missing_is_error=False)
)
for stuff in dataset:
print("#")
for stuf in stuff:
print(type(stuf))
```
Prints:
```python3
#
<class 'imageio.core.util.Array'>
<class 'imageio.core.util.Array'>
<class 'NoneType'>
<class 'NoneType'>
<class 'NoneType'>
<class 'int'>
#
<class 'imageio.core.util.Array'>
<class 'imageio.core.util.Array'>
<class 'imageio.core.util.Array'>
<class 'NoneType'>
<class 'NoneType'>
<class 'int'>
#
<class 'imageio.core.util.Array'>
<class …
```
> Add missing_is_error to Processor.to_tuple port

- .gitignore
- webdataset/autodecode.py
[The precedence of forcing anything with a leading underscore to be decoded as UTF-8](https://github.com/webdataset/webdataset/blob/686438249b13ba304c85d00b472b25438973ce1e/webdataset/autodecode.py#L444), as described in [this issue](https://github.com/webdataset/webdataset/issues/220), causes it to ignore extension-based processing, e.g. for keys that read like "_stuff.flac".  
It seems the original intent of this underscore-processing was to be used for things with *double underscores*, such as `__key__`, etc.  So this PR simply includes a change so that the extension-ignoring UTF-8 decoding only happens for double-underscores.
I also added a couple error messages, e.g. an explicit statement to be printed when asserts fail.
> utf-8 decode only triggers on double-underscore, added error msgs

- webdataset/tariterators.py
The exception handler is currently away from the `tar_file_iterator`. I am not sure that it is intentional or just a typo. 
I feel that it is a typo since the handler is also used to handle the exceptions caused by a sample (instead of a tar file) in group_by_keys. Thus I proposed this one-line change to resolve this issue.
> Pass handler to tar_file_iterator

- webdataset/pipeline.py
This is a quick fix for #297 .
It's not very elegant (maybe we could introduce a "copy constructor" in a `copy` method?) but should solve the issue I was seeing.
> Make pipeline.compose non-destructive

- webdataset/cache.py
WebDataset already supports loading from piped HDFS source like `pipe:hdfs dfs -cat hdfs://DATA_PATH/{000..064}.tar`, but when I use it with caching via `cached_tarfile_to_samples()`, the default `pipe_cleaner` handles everything except `hdfs`. This behavior causes `pipe_cleaner` to return the full string after "pipe" including all spaces, which can be problematic.
I understand that `url_to_name` can be easily overridden (which I did). But it would be better to support it by default since HDFS is also common.
> Handle hdfs url in pipe_cleaner

- webdataset/writer.py
Currently, verbose cannot be entirely overwritten. Consider the following:
```python
with wds.ShardWriter(pattern) as sink:
sink.verbose = False # or sink.verbose = 0
for index, (file, label) in enumerate(data.items()):
sink.write({
...
````
Because of [`self.next_stream()`](https://github.com/webdataset/webdataset/blob/main/webdataset/writer.py#L402) in the constructor, setting verbose after the constructor is not sufficient.
This PR lets verbose be set in the constructor. 
Issue: #133
> For ShardWriter, add verbose as constructor param

- webdataset/filters.py
Currently when using WebDataset inside, say, Jupyter notebooks all the curried pipeline filters have the same generic (and quite confusing) docstrings and argument lists.
This patch uses `functools.update_wrapper` that is used for decorators in the standard library to improve upon this.
I think we could make it even better by making all the function docstrings longer and fit the RestCurried docstring in one line (maybe we cut convert the sentence explaining the "roundabout" into a comment?).
Before:
```
In [2]: wds.to_tuple?
Signature:      wds.to_tuple(*args, **kw)
Type:           RestCurried
String form:    <webdataset.filters.RestCurried object at 0x7fec7e9833d0>
File:           ~/workspace/webdataset/webdataset/filters.py
Docstring:
Helper class for currying pipeline stages.
We use …
```
> Fixup the docstring and argument list of all curried functions.

- webdataset/gopen.py
- webdataset/tariterators.py
Wrap `gopen.gopen` using `with`, which ensures that streams are closed once consumed.
> Close streams once consumed

- webdataset/filters.py
Hi,
This PR is to fix `seed` is not used in `_shuffle()`. This causes dataloaders on the same dataset in different processes are not returning the same indices, which is not desired if we give a seed to it. 
To reproduce the problem at the current release ([0.2.88](https://github.com/webdataset/webdataset/releases/tag/0.2.88)):
```
import os
import random
import numpy as np
import webdataset as wds
import torch
import torch.distributed as dist
from torch import default_generator
from torch.utils.data import TensorDataset
col_1 = TensorDataset(torch.arange(0, 1000))
col_2 = TensorDataset(torch.arange(0, 1000))
col_3 = TensorDataset(torch.arange(0, 1000))
ds = [col_1, col_2, col_3]
def seed_everything(seed):
os.environ["PYTHON_SEED"] = str(seed)
random.seed(seed)
np.random.seed(seed) …
```
> seed is not used in _shuffle()

- webdataset/gopen.py
If you pass a default `file://C:/some/path` URL (e.g. one generated by `pathlib.as_uri()` function), and not a custom `file:C:/some/path` URL, it throws an error `OSError: [Errno 22] Invalid argument: '/C:/some/path` because `pr.path` returns a path with additional slash at the beginning of the path
Adding the `url2pathname` function solves this problem and can possibly solve come other path-related issues.
> Fix additional slash error in Windows pathes

- webdataset/utils.py
I encountered an error when working with webdataset. The `is_iterable` function in `webdataset/utils.py` (line 54) checks that the object type matches the `Iterable` type, but `Iterable` was not imported.
> Fix NameError, forgot to import Iterable

- wids/wids_dl.py
When s3- or local URLS have spaces, we currently get errors. This is a small fix for this.
> fix: allows URLs with spaces

- webdataset/writer.py
This PR adds support for `bz2` and `xz` compression.
While these compression methods are slower than `gz` the reduction in storage and/or bandwidth costs is beneficial for some use cases.
> Add `bz2` and `xz` compression options

- webdataset/writer.py
###Description
* webdataset/writer.py: Add self to opener call in ShardWriter
###Motivation
* ShardWriter broken when using an opener
> Fix: Minor bug in writer.py opener missing self

- wids/wids.py
There seem to be two md5 calculation functions with exactly the same functionality
> Delete redundant md5 calculation function

- wids/wids.py
First of all thanks for the amazing `wids` library!
When training with pytorch lightning in a distributed setting, I got the following error:
```bash
[rank0]: TypeError: You seem to have configured a sampler in your DataLoader which does not provide `__len__` method. The sampler was about to be replaced by `DistributedSamplerWrapper` since `use_distributed_sampler` is True and you are using distributed training. Either provide `__len__` method in your sampler, remove it from DataLoader or set `use_distributed_sampler=False` if you want to handle distributed sampling yourself.
```
Setting `use_distributed_sampler=False` seems to work, but then we lose the information about how big the dataset is (and e.g. have an unknown progress bar length and cannot use epoch-features). Adding `__len__` …
> feat: add __len__ to ChunkedSampler to work with pytorch lightning

- README.md
WebDataset format support was added in `datasets` [2.16.0](https://github.com/huggingface/datasets/releases/tag/2.16.0)
e.g.
```python
from datasets import load_dataset
ds = load_dataset("pixparse/cc12m-wds", streaming=True)
for example in ds["train"]:
...
```
> add hf datasets in supported libraries

- webdataset/shardlists.py
The following iterator would be helpful to use to filter out missing shards:
```
class ShardExistsFilter(Iterator[str]):
"""Simple iterator that filters out shards that don't exist."""
def __init__(self, url: str):
"""
:param url: URL pattern to expand. E.g. /some/path/{000000..000019}.tar
"""
self.url_generator = filter(os.path.exists, braceexpand.braceexpand(url))
def __next__(self) -> Any:
return self.url_generator.__next__()
```
Because of the missing import, we are limited to url strings.
> Missing import prevents iterable objects from being used as url source.
